name: dewddcreative2
main: dewddcreative.Main
version: 1
author: dewtx29@gmail.com
database: false

commands:
  dewbuy:
    description: dewdd creative for buy zone
    usage: /<command>
    aliases: [edewbuyc]
  dewremove:
    description: dewdd creative for remove zone
    usage: /<command>
    aliases: [edewremovec]
  dewset:
    description: dewset is replace everyblock
    usage: /<command>
    aliases: [ds]
  dewfill:
    description: dewfill is fill blocks at space
    usage: /<command>
    aliases: [df]
  dewsetwall:
    description: dewsetwall is replace blocks for build wall
    usage: /<command>
    aliases: [dsw]
  dewfillwall:
    description: dewfillwall is fill blocks for wal
    usage: /<command>
    aliases: [dfw]
  dewa:
    description: dewa is stack selected blocked to some direction
    usage: /<command>
    aliases: [da]
  dewcopy:
    description: dewcopy is copy block to your position.. position will seem place at left click...(select 1)
    usage: /<command>
    aliases: [dc]
  dewdown:
    description: dewdown is put the block on your hand under your feet
    usage: /<command>
    aliases: [dn]
  dewsetlight:
    description: dewsetlight is place torch in the area it's dark
    usage: /<command>
    aliases: [dsl]
  dewspreadcircle:
    description: dewspreadcircle is spread blocks from your position.. to every direction..
    usage: /<command>
    aliases: [dsc]
  dewspreadq:
    description: dewspreadq is spread blocks from your position... only seem y (very fast)
    usage: /<command>
    aliases: [dsq]
  dewbuyremove:
    description: dewbuyremove for admin , remove all protect zone in selected blockb
    usage: /<command>
    aliases: [dbr]
  dewwallcircle:
    description: dewwallcircle is create circle (only wall)
    usage: /<command>
    aliases: [dwc]
  dewsetcircle:
    description: dewsetcircle is create circle (only wall)
    usage: /<command>
  dewfillcircle:
    description: dewfillcircle is create circle (only wall)
    usage: /<command>
    aliases: [dfc]
  loadmainfile:
    description: loadmainfile is force dewset reload world,signfile,deadposition files...
    usage: /<command>
    aliases: [loadmf]
  dewextend:
    description: dewextend set y = 0 to y = 255
    usage: /<command>
    aliases: [de]
  dewselectcube:
    description: dewselectcube select block near you  amount of item in hand = radius
    usage: /<command>
    aliases: [dewselectcube2]
  dewselectprotect:
    description: dewselectprotect select all blocks in protected zone
    usage: /<command>
    aliases: [dewselectprotect2]
  dewfreezone:
    description: dewfreezone go to freezone
    usage: /<command>
    aliases: [dewfreezone2]
    
    
permissions:
  dewdd.creative.overide:
    description: for admin can build every thing at protect zone...
    default: op
  dewdd.creative.dewremove:
    description: for admin can use dewremove
    default: op
  dewdd.creative.changehost:
    description: for admin change [dewhome] change host
    default: op
  dewdd.creative.doprotecty:
    description: for admin can modify at protect y
    default: op
  dewdd.creative.dounprotecty:
    description: for admin can modify at unprotect y
    default: op
  dewdd.creative.dewseteverywhere:
    description: for admin can dewset everywhere
    default: op
