name: dewddcreative
main: dewddcreative.Main
version: 1
author: dewtx29@gmail.com
database: false

commands:
  cre:
    description: dewdd creative
    usage: /<command>
    
permissions:
  dewdd.creative.overide:
    description: for admin can build every thing at protect zone...
    default: op
  dewdd.creative.dewremove:
    description: for admin can use dewremove
    default: op
  dewdd.creative.changehost:
    description: for admin change [dewhome] change host
    default: op
  dewdd.creative.doprotecty:
    description: for admin can modify at protect y
    default: op
  dewdd.creative.dounprotecty:
    description: for admin can modify at unprotect y
    default: op
