name: dewddgravity
main: dewddgravity.Main
version: 1
author: dewtx29@gmail.com
database: false
depend: [dewddprint, dewddtran]

commands:
  gravity:
    description: access gravity commands
    usage: /<command>
    
