name: dewddinv
main: dewddinv.Main
version: 1
author: dewtx29@gmail.com
database: false

commands:
  dinvl:
    description: open last inventory
    usage: /<command>
  dinv:
    description: open visual chest by dewdd
    usage: /<command>
  dinvload:
    description: load file
    usage: /<command>
  dinvsave:
    description: save file
    usage: /<command>
    
