name: dewddft
main: dewddft.Main
version: 1
author: dewtx29@gmail.com
database: false
depend: [dewset, dewddprint, dewddtran]

commands:
  dft:
    description: dew free item command...
    usage: /<command>
  dnick:
    description: set prefix and suffix name...
    usage: /<command>
    
