name: dewddskyblock
main: dewddskyblock.Main
version: 1
author: dewtx29@gmail.com
database: false
depend: [dewddprint, dewddtran]

commands:
  skyblock:
    description: can use /skyblock , /sky commands ( need to add for all player)
    usage: /<command>
    aliases: [sky,is]
    permissions: dewdd.skyblock.skyblock

permissions:
  dewdd.skyblock.overide:
    description: can do anything as everyone skyblock
    default: op
  dewdd.skyblock.resetlv:
    description: can reset challenge lv of everyone skyblock
    default: op

