name: dewddskyblock
main: dewddskyblock.Main
version: 1
author: dewtx29@gmail.com
database: false

commands:
  skyblock:
    description: skyblock for random teleport to skyblock
    usage: /<command>
    aliases: [sky]
    permissions: dewdd.skyblock.skyblock

