name: dewddadmin
main: dewddadmin.Main
version: 1
author: dewtx29@gmail.com
database: false

commands:
  dewreloadadminfile:
    description: reloadadminfile
    usage: /<command>
    aliases: [reloadadmin]

permissions:
  dewdd.admin.default:
    description: mark player as default
    default: op
  dewdd.admin.vip:
    description: mark player as vip
    default: op
  dewdd.admin.moderator:
    description: mark player as builder
    default: op
  dewdd.admin.admin:
    description: mark player as admin
    default: op
