name: dewddredstoneexperimental
main: dewdd_redstone_experimental.Main
version: 1
author: dewtx29@gmail.com
database: false
depend: [dewddprint, dewddtran]

commands:
  redex:
    description: use redstone experimental
    usage: /<command>
    permissions: dewdd.redex.run

