name: dewddautomessage
main: dewddautomessage.Main
version: 1
author: dewtx29@gmail.com
database: false
depend: [dewddprint]

commands:
  dewddreloadmessagefile:
    description: dewdd automessage reload file
    usage: /<command>
    aliases: [edewddreloadmessagefile]
