name: dewddsetline
main: dewddsetline.Main
version: 1
author: dewtx29@gmail.com
database: false

commands:
  dewsetline:
    description: dewsetline if for set new line
    usage: /<command> [line] [message]

permissions:
  dewdd.private.overide:
    description: for admin can open any chest...
    default: op
  dewdd.private.setline.everysign:
    description: for admin reset line every sign
    default: op
