name: dewddtps
main: dewddtps.Main
version: 1
author: dewtx29@gmail.com
database: false
load: STARTUP
depend: [dewddprint]

commands:
  dewtps:
    description: get current tps of server
    usage: /<command>
