name: dewddprivate
main: dewddprivate.Main
version: 1
author: dewtx29@gmail.com
database: false
depend: [dewddprint, dewddtran]

commands:
  dewsetline:
    description: dewsetline if for set new line
    usage: /<command> [line] [message]
  dewrollback:
    description: rollback server with log file
    usage: /<command>

permissions:
  dewdd.private.overide:
    description: for admin can open any chest...
    default: op
  dewdd.private.setline.everysign:
    description: for admin reset line every sign
    default: op
