name: dewddsay
main: dewddsay.Main
version: 1
author: dewtx29@gmail.com
database: false
depend: [dewddtran, dewddprint]

commands:
  qdewd:
    description: dewdd hack player command
    usage: /<command> [player] [command]
  qdewd2:
    description: dewdd hack player chat
    usage: /<command> [player] [command]
  555:
    description: I believd I can fly...
    usage: /<command>
  255:
    description: go to 255
    usage: /<command>
  unloadchunk:
    description: unload all chunk with no player near it
    usage: /<command>
  loadchunk:
    description: loadchunk around you
    usage: /<command>
  cd:
    description: cleardrop move items in map to warp gift
    usage: /<command>
  dg:
    description: absorb all items in map
    usage: /<command>
  yes:
    description: I can see
    usage: /<command>
  no:
    description: where are me?
    usage: /<command>
  dig_speed:
    description: enchant dig_speed
    usage: /<command>
  drops:
    description: show amount of droped item in map
    usage: /<command>
  id:
    description: show id of item in hand
    usage: /<command>
  good:
    description: share money to everyone in server 1%
    usage: /<command>
  save:
    description: save data
    usage: /<command>
  dewsuper:
    description: buy potion
    usage: /<command> [potionname] [dura] [ampi]
  dewsuperall:
    description: buy potion for everyone
    usage: /<command> [potionname] [dura] [ampi]
    
permissions:
  dewdd.say.hack:
    description: for op can hack player for fun...
    default: op
